# Generated by Django 2.0 on 2018-01-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addclient',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
