# Generated by Django 2.0 on 2018-01-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_addclient_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='addclient',
            name='email_org',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='introduction',
            field=models.TextField(default=1, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='logo',
            field=models.ImageField(default='common/files/images/display.png', upload_to='common/files/images'),
        ),
        migrations.AddField(
            model_name='addclient',
            name='ownership_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
