# Generated by Django 2.0 on 2018-01-29 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_auto_20180129_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corecontactpersondetail',
            old_name='client_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='corecontactpersondetail',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_billinginfo', to='client.AddClient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_billinginfo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_branch', to='client.AddClient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessoutflow',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_businessoutflow', to='client.AddClient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corecontactpersondetail',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_corecontactpersondetail', to='client.AddClient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corecontactpersondetail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_corecontactpersondetail', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headoforganization',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_headoforganization', to='client.AddClient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headoforganization',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_headoforganization', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listservice',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_listservice', to='client.AddClient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referenceclient',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_referenceclient', to='client.AddClient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referenceclient',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_referenceclient', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
