# Generated by Django 2.0 on 2018-01-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20180129_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='client',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='client',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='user',
        ),
        migrations.RemoveField(
            model_name='businessoutflow',
            name='client',
        ),
        migrations.RemoveField(
            model_name='businessoutflow',
            name='user',
        ),
        migrations.RemoveField(
            model_name='corecontactpersondetail',
            name='client',
        ),
        migrations.RemoveField(
            model_name='corecontactpersondetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='headoforganization',
            name='client',
        ),
        migrations.RemoveField(
            model_name='headoforganization',
            name='user',
        ),
        migrations.RemoveField(
            model_name='listservice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='listservice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='referenceclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='referenceclient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='addclient',
            name='created',
        ),
        migrations.AddField(
            model_name='addclient',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addclient',
            name='billing_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='branch_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='branch_email',
            field=models.EmailField(default='akashsky1313@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='branch_incharge',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='branch_phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='designation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='email_head',
            field=models.EmailField(default='akaahs@jdksd.cjd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='facebook_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='linked_in_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='mobile_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='mobile_no_head',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='office_phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='outflowed_to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='pan_no',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='reference_website',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='service_detail',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='service_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='service_outflowed',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='social_media_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='social_media_id_head',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BillingInfo',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='BusinessOutflow',
        ),
        migrations.DeleteModel(
            name='CoreContactPersonDetail',
        ),
        migrations.DeleteModel(
            name='HeadOfOrganization',
        ),
        migrations.DeleteModel(
            name='ListService',
        ),
        migrations.DeleteModel(
            name='ReferenceClient',
        ),
    ]
