# Generated by Django 2.0 on 2018-01-29 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0007_addclient_outflow_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOutflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outflowed_to', models.CharField(max_length=255)),
                ('service_outflowed', models.CharField(max_length=255)),
                ('outflow_date', models.DateField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='addclient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='addclient',
            name='outflow_date',
        ),
        migrations.RemoveField(
            model_name='addclient',
            name='outflowed_to',
        ),
        migrations.RemoveField(
            model_name='addclient',
            name='service_outflowed',
        ),
        migrations.AddField(
            model_name='businessoutflow',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_businessoutflow', to='client.AddClient'),
        ),
        migrations.AddField(
            model_name='businessoutflow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_businessoutflow', to=settings.AUTH_USER_MODEL),
        ),
    ]
