# Generated by Django 2.0 on 2018-01-29 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20180129_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='addclient',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addclient',
            name='billing_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='branch_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='branch_email',
            field=models.EmailField(default='akash@ajkjask.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='branch_incharge',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='branch_phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='addclient',
            name='designation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='email',
            field=models.EmailField(default='ajh@jkhd.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='email_head',
            field=models.EmailField(default='asjk@jkas.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='email_org',
            field=models.EmailField(default='asj@jask.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='facebook_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='introduction',
            field=models.TextField(default=1, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='linked_in_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='logo',
            field=models.ImageField(default='common/files/images/display.png', upload_to='common/files/images'),
        ),
        migrations.AddField(
            model_name='addclient',
            name='mobile_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='mobile_no_head',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='office_phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='outflow_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='outflowed_to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='ownership_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='pan_no',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='reference_website',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='service_outflowed',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='social_media_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclient',
            name='social_media_id_head',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
