# Generated by Django 2.0 on 2018-01-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20180129_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='addclient',
            name='designation_contactperson',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
