# Generated by Django 2.0.1 on 2018-01-12 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_auto_20180112_0133'),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlist',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='lead.LeadProcess'),
            preserve_default=False,
        ),
    ]
