# Generated by Django 2.0.1 on 2018-01-12 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_clientlist_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substage', models.CharField(max_length=100)),
                ('sales_stage', models.CharField(choices=[('Suspecting', 'Suspecting'), ('Prospecting', 'Prospecting'), ('Approaching', 'Approaching')], max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_sales', to='communication.Clientlist')),
            ],
        ),
    ]
