# Generated by Django 2.0 on 2018-01-17 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_auto_20180117_0717'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0002_clientlist_client_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_pic', models.ImageField(default='common/files/images/display.png', upload_to='common/files/images')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('medium', models.CharField(choices=[('Inbound Call', 'Inbound Call'), ('Outbound Call', 'Outbound Call'), ('Inbound Email', 'Inbound Email'), ('Outbound Email', 'Outbound Email'), ('Inbound Call', 'Inbound Call'), ('Outbound Call', 'Outbound Call')], max_length=255)),
                ('medium_status', models.CharField(choices=[('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], max_length=10)),
                ('contact_person', models.CharField(max_length=255)),
                ('remarks', models.TextField(max_length=999)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='lead.LeadProcess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientlist',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='clientlist',
            name='user',
        ),
        migrations.AlterField(
            model_name='salesstage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_sales', to='communication.ClientDetail'),
        ),
        migrations.AlterField(
            model_name='salessub',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_salessub', to='communication.ClientDetail'),
        ),
        migrations.DeleteModel(
            name='Clientlist',
        ),
    ]
