# Generated by Django 2.0.1 on 2018-01-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_salesstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_substage', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_salessub', to='communication.Clientlist')),
                ('substage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_stage', to='communication.SalesStage')),
            ],
        ),
    ]
