# Generated by Django 2.0 on 2018-01-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20180117_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_incharge', models.CharField(max_length=255)),
                ('branch_address', models.CharField(max_length=255)),
                ('branch_phone', models.CharField(max_length=255)),
                ('branch_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOutflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outflowed_to', models.CharField(max_length=255)),
                ('service_outflowed', models.CharField(max_length=255)),
                ('outflow_date', models.DateField()),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ListService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_detail', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientdetail',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='clientdetail',
            name='medium_status',
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='address',
            field=models.CharField(default='Kathmandu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='billing_name',
            field=models.CharField(default='Mr. Foo Bar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='client_value',
            field=models.CharField(choices=[('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], default='High', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='designation',
            field=models.CharField(default='Manager', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='email_head',
            field=models.EmailField(default='test@test.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='email_org',
            field=models.EmailField(default='test@test.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='employee_size',
            field=models.CharField(choices=[('1-10', '1-10'), ('10-50', '10-50'), ('50-100', '50-100'), ('100-500', '100-500'), ('500+', '500+')], default='1-10', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='facebook_id',
            field=models.CharField(default='akashbrt', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='group_of_companies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='introduction',
            field=models.TextField(default='This is awesome', max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='linked_in_id',
            field=models.CharField(default='akashadh', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='mobile_no',
            field=models.IntegerField(default=9842044452),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='mobile_no_head',
            field=models.IntegerField(default=9842155455),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='office_phone',
            field=models.IntegerField(default=532998),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='organisation_name',
            field=models.CharField(default='Apple Inc.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='ownership_type',
            field=models.CharField(default='Totalitarian', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='pan_no',
            field=models.CharField(default=22554455, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='phone_number',
            field=models.IntegerField(default=232),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='reference_website',
            field=models.CharField(default='www.google.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='social_media_id',
            field=models.CharField(default='akasshsh', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='social_media_id_head',
            field=models.CharField(default='aasdjs', max_length=255),
            preserve_default=False,
        ),
    ]
