# Generated by Django 2.0 on 2018-01-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_auto_20180122_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nameoforganization',
            name='client_pic',
        ),
        migrations.RemoveField(
            model_name='nameoforganization',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='nameoforganization',
            name='remarks',
        ),
    ]
