# Generated by Django 2.0 on 2018-01-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_auto_20180122_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nameoforganization',
            name='email_org',
        ),
        migrations.RemoveField(
            model_name='nameoforganization',
            name='group_of_companies',
        ),
        migrations.RemoveField(
            model_name='nameoforganization',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='nameoforganization',
            name='ownership_type',
        ),
        migrations.RemoveField(
            model_name='nameoforganization',
            name='phone_number',
        ),
    ]
