# Generated by Django 2.0 on 2018-01-22 06:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0008_auto_20180122_0554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NameOfOrganization',
            new_name='AddClient',
        ),
    ]
