# Generated by Django 2.0 on 2018-01-22 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0009_auto_20180122_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=255)),
                ('medium', models.CharField(choices=[('Inbound Call', 'Inbound Call'), ('Outbound Call', 'Outbound Call'), ('Inbound Email', 'Inbound Email'), ('Outbound Email', 'Outbound Email'), ('SMS', 'SMS'), ('Meeting', 'Meeting')], max_length=255)),
                ('sales_stage', models.CharField(choices=[('Suspecting', 'Suspecting'), ('Prospecting', 'Prospecting'), ('Approaching', 'Approaching'), ('Negotiation', 'Negotiation'), ('Sales Lead', 'Sales Lead'), ('Value Proposition', 'Value Proposition')], max_length=255)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='addclient',
            name='user',
        ),
        migrations.DeleteModel(
            name='BillingInfo',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='user',
        ),
        migrations.RemoveField(
            model_name='businessoutflow',
            name='user',
        ),
        migrations.DeleteModel(
            name='CoreContactPersonDetail',
        ),
        migrations.DeleteModel(
            name='HeadOfOrganization',
        ),
        migrations.RemoveField(
            model_name='listservice',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReferenceClient',
        ),
        migrations.DeleteModel(
            name='AddClient',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='BusinessOutflow',
        ),
        migrations.DeleteModel(
            name='ListService',
        ),
    ]
