# Generated by Django 2.0 on 2018-01-22 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0010_auto_20180122_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcommunication',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_add_communication', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
