# Generated by Django 2.0 on 2018-01-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_addcommunication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcommunication',
            name='user',
        ),
    ]
