# Generated by Django 2.0 on 2018-01-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('communication', '0013_auto_20180122_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcommunication',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_addcommunication', to='client.AddClient'),
            preserve_default=False,
        ),
    ]
