# Generated by Django 2.0 on 2018-01-23 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
        ('communication', '0014_addcommunication_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showed_interest_for_later', models.DateField()),
                ('preferred_competitors', models.CharField(max_length=255)),
                ('not_interested', models.BooleanField(default=False)),
                ('dont_call_again', models.BooleanField(default=False)),
                ('interest_in_other_HR', models.BooleanField(default=False)),
                ('remarks', models.TextField(max_length=999)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_prospecting', to='client.AddClient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prospecting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suspecting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_verification', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_suspecting', to='client.AddClient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_suspecting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
