# Generated by Django 2.0 on 2018-01-23 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0015_prospecting_suspecting'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspecting',
            name='communications',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='add_comunications', to='communication.AddCommunication'),
            preserve_default=False,
        ),
    ]
