# Generated by Django 2.0 on 2018-01-23 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0016_suspecting_communications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_introduction', models.CharField(max_length=255)),
                ('business_renewal', models.CharField(max_length=255)),
                ('submit_proposal', models.CharField(max_length=255)),
                ('presentation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_discussion', models.CharField(max_length=255)),
                ('discount_discussion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_generation', models.BooleanField(default=False)),
                ('invoice_approval', models.CharField(max_length=255)),
                ('job_post', models.CharField(max_length=255)),
                ('pre_design', models.CharField(max_length=255)),
                ('approval_on_progress', models.CharField(max_length=255)),
                ('billing_process', models.CharField(max_length=255)),
                ('payment_on_progress', models.CharField(max_length=255)),
                ('payment_received', models.CharField(max_length=255)),
                ('payment_verified', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='suspecting',
            name='communications',
        ),
        migrations.AddField(
            model_name='addcommunication',
            name='suspecting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='susp_addcommunication', to='communication.Suspecting'),
            preserve_default=False,
        ),
    ]
