# Generated by Django 2.0 on 2018-01-23 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0018_remove_addcommunication_suspecting'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspecting',
            name='communication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='communication_suspecting', to='communication.AddCommunication'),
            preserve_default=False,
        ),
    ]
