# Generated by Django 2.0 on 2018-01-23 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0019_suspecting_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecting',
            name='communication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='communication_prospecting', to='communication.AddCommunication'),
            preserve_default=False,
        ),
    ]
