# Generated by Django 2.0 on 2018-01-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0021_auto_20180123_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='communication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='communication_negotiation', to='communication.AddCommunication'),
            preserve_default=False,
        ),
    ]
