# Generated by Django 2.0 on 2018-01-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('communication', '0022_negotiation_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='approaching',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_approaching', to='client.AddClient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negotiation',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_negotiation', to='client.AddClient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleslead',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_saleslead', to='client.AddClient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleslead',
            name='communication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='communication_saleslead', to='communication.AddCommunication'),
            preserve_default=False,
        ),
    ]
