# Generated by Django 2.0 on 2018-01-24 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0023_auto_20180123_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcommunication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
