# Generated by Django 2.0 on 2018-01-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0025_auto_20180125_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcommunication',
            name='medium_direction',
            field=models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addcommunication',
            name='medium',
            field=models.CharField(choices=[('Call', 'Call'), ('Email', 'Email'), ('SMS', 'SMS'), ('Meeting', 'Meeting')], max_length=255),
        ),
    ]
