# Generated by Django 2.0 on 2018-01-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0026_auto_20180126_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approaching',
            name='business_renewal',
        ),
        migrations.RemoveField(
            model_name='approaching',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='approaching',
            name='service_introduction',
        ),
        migrations.RemoveField(
            model_name='approaching',
            name='submit_proposal',
        ),
        migrations.RemoveField(
            model_name='negotiation',
            name='discount_discussion',
        ),
        migrations.RemoveField(
            model_name='negotiation',
            name='service_discussion',
        ),
        migrations.RemoveField(
            model_name='prospecting',
            name='dont_call_again',
        ),
        migrations.RemoveField(
            model_name='prospecting',
            name='interest_in_other_HR',
        ),
        migrations.RemoveField(
            model_name='prospecting',
            name='not_interested',
        ),
        migrations.RemoveField(
            model_name='prospecting',
            name='preferred_competitors',
        ),
        migrations.RemoveField(
            model_name='prospecting',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='prospecting',
            name='showed_interest_for_later',
        ),
        migrations.RemoveField(
            model_name='suspecting',
            name='contact_verification',
        ),
        migrations.AddField(
            model_name='approaching',
            name='approaching_substages',
            field=models.CharField(choices=[('a1', 'Service Introduction'), ('a2', 'Business Renewal'), ('a3', 'Submit Proposal'), ('a4', 'Presentation')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negotiation',
            name='negotiation_substages',
            field=models.CharField(choices=[('n1', 'Service Discussion'), ('n2', 'Discount Discussion')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospecting',
            name='prospecting_substages',
            field=models.CharField(choices=[('p1', 'Add Client Detail'), ('p2', 'Introduce Service'), ('p3', 'Showed Interest For Now'), ('p4', 'Showed Interest For Later'), ('p5', 'Preferred Competitors'), ('p6', 'Not Interested'), ('p7', 'Dont Call Me Again'), ('p8', 'Interest In Other HR Service')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspecting',
            name='suspecting_substages',
            field=models.CharField(choices=[('s1', 'Contact Verification')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
