# Generated by Django 2.0 on 2018-01-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadprocess',
            old_name='income',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='leadprocess',
            old_name='service',
            new_name='service_type',
        ),
        migrations.RenameField(
            model_name='leadprocess',
            old_name='tax_percent',
            new_name='vat_percent',
        ),
        migrations.RemoveField(
            model_name='leadprocess',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='leadprocess',
            name='status',
        ),
        migrations.RemoveField(
            model_name='leadprocess',
            name='unit',
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='billing_name',
            field=models.CharField(default='Mr. Nobody', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='client_address',
            field=models.CharField(default='Kathmandu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='client_value',
            field=models.CharField(choices=[('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], default='High', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='contact_person',
            field=models.CharField(default='Mr. Foo Bar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='discount_entry',
            field=models.CharField(choices=[('Flat', 'Percentage'), ('Flat', 'Percentage')], default='Flat', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='employer_name',
            field=models.CharField(default='Ram', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='last_communicated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='last_service_name',
            field=models.CharField(default='Last service', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='last_service_taken',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='last_status',
            field=models.CharField(choices=[('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], default='Successful', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='pan_no',
            field=models.CharField(default=392839283980, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='post_choice',
            field=models.CharField(choices=[('Days Duration', 'Days Duration'), ('Job Unit', 'Job Unit')], default='Job Unit', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='post_type',
            field=models.CharField(choices=[('Top Jobs', 'Top Jobs'), ('Hot Jobs', 'Hot Jobs'), ('F. Post', 'F. Post'), ('G. Post', 'G. Post')], default='Top Jobs', max_length=15),
            preserve_default=False,
        ),
    ]
