# Generated by Django 2.0.1 on 2018-01-12 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Puppy',
            new_name='LeadProcess',
        ),
    ]
