# Generated by Django 2.0 on 2018-01-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20180116_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadprocess',
            name='discount_entry',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Percentage', 'Percentage')], max_length=255),
        ),
        migrations.AlterField(
            model_name='leadprocess',
            name='vat_percent',
            field=models.PositiveIntegerField(default=13),
        ),
    ]
