# Generated by Django 2.0.1 on 2018-01-12 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0002_auto_20180112_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadprocess',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='leadprocess',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='leadprocess',
            name='age',
        ),
        migrations.RemoveField(
            model_name='leadprocess',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='leadprocess',
            name='color',
        ),
        migrations.RemoveField(
            model_name='leadprocess',
            name='name',
        ),
        migrations.RemoveField(
            model_name='leadprocess',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='bulk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='service',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='stage',
            field=models.PositiveIntegerField(default=1, validators=[rest_framework.compat.MinValueValidator(1), rest_framework.compat.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='tax_percent',
            field=models.PositiveIntegerField(default=1, validators=[rest_framework.compat.MinValueValidator(1), rest_framework.compat.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='unit',
            field=models.PositiveIntegerField(default=1, validators=[rest_framework.compat.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='leadprocess',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
